spring:
  main.banner-mode: off

server:
  port: 8080
  tomcat.accesslog.enabled: true

management:
  endpoint.prometheus.enabled: true
  endpoints:
    web.base-path: /
    enabled-by-default: false
    web.exposure.include: prometheus
    web.path-mapping.prometheus: prometheus-metrics

springdoc:
  show-actuator: true
  swagger-ui:
    displayRequestDuration: true
    path: /apidoc
    tryItOutEnabled: true
