spring:
  main.banner-mode: off

server:
  port: 8080
  tomcat.accesslog.enabled: true
  forward-headers-strategy: framework

management:
  endpoint.prometheus.access: unrestricted
  endpoints:
    web.base-path: /
    access.default: none
    web.exposure.include: prometheus
    web.path-mapping.prometheus: prometheus-metrics

springdoc:
  model-and-view-allowed: true
  show-actuator: true
  api-docs:
    path: /apidoc-json
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    try-it-out-enabled: true
    path: /apidoc
