spring:
  main.banner-mode: off

server:
  port: 8080
  tomcat.accesslog.enabled: true
  forward-headers-strategy: framework

management:
  endpoint.prometheus.enabled: true
  endpoints:
    web.base-path: /
    enabled-by-default: false
    web.exposure.include: prometheus
    web.path-mapping.prometheus: prometheus-metrics

springdoc:
  model-and-view-allowed: true
  show-actuator: true
  swagger-ui:
    displayRequestDuration: true
    tryItOutEnabled: true
    use-root-path: true
